// This file is auto-generated by @hey-api/openapi-ts

export const ApiResponseSchema = {
    required: ['isSuccess'],
    type: 'object',
    properties: {
        isSuccess: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const ConfigurationApiResponseSchema = {
    required: ['data', 'isSuccess'],
    type: 'object',
    properties: {
        isSuccess: {
            type: 'boolean'
        },
        data: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/PreviewConfiguration'
                }
            ]
        }
    },
    additionalProperties: false
} as const;

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const PreviewConfigurationSchema = {
    required: ['configuredFromSettingsFileOrCode', 'disabled', 'previewModeSettings', 'templateUrl'],
    type: 'object',
    properties: {
        templateUrl: {
            type: 'string'
        },
        previewModeSettings: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/PreviewModeSettingContentType'
                    },
                    {
                        '$ref': '#/components/schemas/PreviewModeSettingNodeId'
                    }
                ]
            }
        },
        disabled: {
            type: 'boolean'
        },
        configuredFromSettingsFileOrCode: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const PreviewModeSchema = {
    enum: ['UseHeadlessPreview', 'UseStandardPreview', 'DisablePreview'],
    type: 'string'
} as const;

export const PreviewModeApiResponseSchema = {
    required: ['data', 'isSuccess'],
    type: 'object',
    properties: {
        isSuccess: {
            type: 'boolean'
        },
        data: {
            oneOf: [
                {
                    '$ref': '#/components/schemas/PreviewModeResponse'
                }
            ]
        }
    },
    additionalProperties: false
} as const;

export const PreviewModeResponseSchema = {
    required: ['previewMode'],
    type: 'object',
    properties: {
        previewMode: {
            '$ref': '#/components/schemas/PreviewMode'
        }
    },
    additionalProperties: false
} as const;

export const PreviewModeSettingContentTypeSchema = {
    required: ['contentTypes', 'mode', 'type'],
    type: 'object',
    properties: {
        type: {
            '$ref': '#/components/schemas/PreviewModeSettingType'
        },
        contentTypes: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        mode: {
            '$ref': '#/components/schemas/PreviewMode'
        }
    },
    additionalProperties: false
} as const;

export const PreviewModeSettingNodeIdSchema = {
    required: ['includeDescendants', 'mode', 'nodeIds', 'type'],
    type: 'object',
    properties: {
        type: {
            '$ref': '#/components/schemas/PreviewModeSettingType'
        },
        nodeIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int32'
            }
        },
        includeDescendants: {
            type: 'boolean'
        },
        mode: {
            '$ref': '#/components/schemas/PreviewMode'
        }
    },
    additionalProperties: false
} as const;

export const PreviewModeSettingTypeSchema = {
    enum: ['ContentType', 'NodeId'],
    type: 'string'
} as const;