// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetConfigurationError, GetConfigurationResponse, GetPreviewModeData, GetPreviewModeError, GetPreviewModeResponse, SaveConfigurationData, SaveConfigurationError, SaveConfigurationResponse } from './types.gen';

export const client = createClient(createConfig());

export class OurUmbracoHeadlessPreviewService {
    public static getConfiguration<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetConfigurationResponse, GetConfigurationError, ThrowOnError>({
            ...options,
            url: '/umbraco/headlesspreview/api/v1/GetConfiguration'
        });
    }
    
    public static getPreviewMode<ThrowOnError extends boolean = false>(options?: Options<GetPreviewModeData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPreviewModeResponse, GetPreviewModeError, ThrowOnError>({
            ...options,
            url: '/umbraco/headlesspreview/api/v1/GetPreviewMode'
        });
    }
    
    public static saveConfiguration<ThrowOnError extends boolean = false>(options?: Options<SaveConfigurationData, ThrowOnError>) {
        return (options?.client ?? client).post<SaveConfigurationResponse, SaveConfigurationError, ThrowOnError>({
            ...options,
            url: '/umbraco/headlesspreview/api/v1/SaveConfiguration'
        });
    }
    
}